global:
  scrape_interval: 15s  # Intervalo de recolección de métricas

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "172.17.0.1:9090" ]

  - job_name: "node_exporter"
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: 'shortlinker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.33:8085']